### PR TITLE
fix current version

### PR DESCRIPTION
**Pull request by okawa-h**
hello.

It corresponds to the current version.
Could you merge if you like?

thanks :)

### CODE REVIEW

**Comment by luizbills** [comment]
@okawa-h have you tested?

**Comment by okawa-h** [comment]
yes, working.

**Comment by luizbills** [comment]
@okawa-h what command I should execute to publish a new version?
I'm years without working with haxe.

**Comment by okawa-h** [comment]
@luizbills 
thank for marged😀

```shell
haxelib submit [project.zip]
```
Please refer to the bottom of the page.
https://lib.haxe.org/documentation/using-haxelib/

Please use haxe occasionally

**Comment by luizbills** [comment]
published https://lib.haxe.org/p/stats.js.hx/0.1.0
Thanks!

**Pull request merged**
